export const clientsData = [
  {
    id: 1,
    name: 'Tech Innovators Inc.',
    vatCode: 'BE0123456789',
    address: '123 Innovation Drive, Brussels, Belgium',
    email: 'info@techinnovators.com',
    registrations: 15,
  },
  {
    id: 2,
    name: 'Global Logistics Ltd.',
    vatCode: 'BE0987654321',
    address: '45 Cargo Lane, Antwerp, Belgium',
    email: 'contact@globallogistics.com',
    registrations: 8,
  },
  {
    id: 3,
    name: 'Healthcare Solutions Group',
    vatCode: 'BE1122334455',
    address: '88 Wellness Road, Ghent, Belgium',
    email: 'support@healthcaregroup.com',
    registrations: 20,
  },
  {
    id: 4,
    name: 'Creative Minds Agency',
    vatCode: 'BE2233445566',
    address: '12 Art Lane, Leuven, Belgium',
    email: 'hello@creativeminds.com',
    registrations: 5,
  },
  {
    id: 5,
    name: 'GreenTech Solutions',
    vatCode: 'BE3344556677',
    address: '72 Eco Street, Bruges, Belgium',
    email: 'info@greentech.com',
    registrations: 12,
  },
  {
    id: 6,
    name: 'Smart Manufacturing Corp.',
    vatCode: 'BE4455667788',
    address: '34 Industrial Blvd, Charleroi, Belgium',
    email: 'contact@smartmanufacturing.com',
    registrations: 10,
  },
  {
    id: 7,
    name: 'Educational Horizons',
    vatCode: 'BE5566778899',
    address: '56 Knowledge Avenue, Liege, Belgium',
    email: 'admin@eduhorizons.com',
    registrations: 25,
  },
  {
    id: 8,
    name: 'IT Pioneers Ltd.',
    vatCode: 'BE6677889900',
    address: '99 Tech Valley, Namur, Belgium',
    email: 'support@itpioneers.com',
    registrations: 18,
  },
  {
    id: 9,
    name: 'NextGen Retailers',
    vatCode: 'BE7788990011',
    address: '8 Market Street, Mons, Belgium',
    email: 'sales@nextgenretail.com',
    registrations: 7,
  },
  {
    id: 10,
    name: 'Sustainable Future Inc.',
    vatCode: 'BE8899001122',
    address: '123 Green Lane, Tournai, Belgium',
    email: 'hello@sustainablefuture.com',
    registrations: 14,
  },
  {
    id: 11,
    name: 'Logistics Network Group',
    vatCode: 'BE9900112233',
    address: '456 Cargo Avenue, Antwerp, Belgium',
    email: 'info@logisticsnetwork.com',
    registrations: 22,
  },
  {
    id: 12,
    name: 'Finance Experts Ltd.',
    vatCode: 'BE1011123344',
    address: '98 Treasury Street, Brussels, Belgium',
    email: 'contact@financeexperts.com',
    registrations: 9,
  },
  {
    id: 13,
    name: 'Urban Development Partners',
    vatCode: 'BE1122334455',
    address: '22 Cityscape Blvd, Ghent, Belgium',
    email: 'info@urbanpartners.com',
    registrations: 6,
  },
  {
    id: 14,
    name: 'Energy Innovators',
    vatCode: 'BE1223344556',
    address: '78 Power Plant Lane, Liege, Belgium',
    email: 'admin@energyinnovators.com',
    registrations: 19,
  },
  {
    id: 15,
    name: 'Digital Marketing Agency',
    vatCode: 'BE1334455667',
    address: '12 Ad Street, Leuven, Belgium',
    email: 'support@digitalmarketing.com',
    registrations: 8,
  },
];
